nome = input('Qual é o seu nome?' )
idade = int(input('Qual é a sua idade?'))
programacao = input('Qual é a sua linguagem de programação favorita?')
print(f"meu nome: {nome}\nminha idade:{idade}\nLinguagem favorita: {programacao}".format(nome, idade, programacao) )
ano_atual = int(input('Em que ano estamos?') )
ano_nascimento = (ano_atual-idade)
print (f'ano atual: {ano_atual} - idade {idade} = ano nascimento: {ano_nascimento}')
